### PR TITLE
check if the response is not empty before save to cache

### PR DESCRIPTION
**Pull request by halink0803**

### CODE REVIEW

**Review by CaoManhDat — COMMENTED** [review]
can we use error from `self.call` to check whether it is reverted or not?

**Comment by halink0803** [comment]
> can we use error from `self.call` to check whether it is reverted or not?

I agree, because sometimes empty is also a valid response, let me update it.

**Comment by halink0803** [comment]
> can we use error from `self.call` to check whether it is reverted or not?

I checked the docs for function `map(move |result| {})` and it is only be invoked when the `future` (return from call) is resolved. If `call` function return error or panic, the map result will not be invoked. We can add the `map_err` function to handle the error from `future` return but it might not necessary.

**Comment by CaoManhDat** [comment]
Got it, so LGTM!

**Review by CaoManhDat — APPROVED** [review]

**Review by CaoManhDat — APPROVED** [review]

**Pull request merged**
