### PR TITLE
Add metrics subgraph name

### PR DESCRIPTION
**Pull request by halink0803**

### CODE REVIEW

**Comment by vutran1710** [comment]
@halink0803 any update on this? And since we already have deployment-hash, why need subgraph-name?

**Comment by halink0803** [comment]
@vutran1710 deploymentHash is not user friendly, when we look at deployment_hash, we have no idea what subgraph it is. However, as I tested in local env then this PR is not satisfied us as it will add name like sgd1, sgd2, sgd3 instead of the real name like elastic-subgraph. The PR need to be updated.

**Comment by vutran1710** [comment]
> @vutran1710 deploymentHash is not user friendly, when we look at deployment_hash, we have no idea what subgraph it is. However, as I tested in local env then this PR is not satisfied us as it will add name like sgd1, sgd2, sgd3 instead of the real name like elastic-subgraph. The PR need to be updated.

This approach does not seem good since it involves heavy editing. A better approach might be implementing method `as_str` for DeploymentHash type and have it returned both hash+alias

**Comment by halink0803** [comment]
> This approach does not seem good since it involves heavy editing. A better approach might be implementing method as_str for DeploymentHash type and have it returned both hash+alias

As I check then `DeploymentHash` is only wrap of String, could we add more information to it then? 

```rust
/// The IPFS hash used to identifiy a deployment externally, i.e., the
/// `Qm..` string that `graph-cli` prints when deploying to a subgraph
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct DeploymentHash(String);
```

**Pull request closed without merging**
